version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 08041984
      MYSQL_DATABASE: chita_development
  chita:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/chita
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db